layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:

  - name: Data Engineering
    web_url: https://github.com/topics/data-engineering
    image_url: http://wfarm2.dataknet.com/static/resources/icons/set113/52641ba2.png

  - name: Rust
    web_url: https://github.com/topics/rust
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/rust/rust.png

  - name: Pytorch
    web_url: https://github.com/topics/pytorch
    image_url: https://pytorch.org/assets/images/pytorch-logo.png

  - name: ML Ops / Production pipelines
    web_url: https://github.com/topics/ml-ops
    image_url: https://www.contentcaptureservices.co.uk/wp-content/uploads/2018/11/Machine_Learning-300x300.png

  - name: Philosophy and logic
    web_url: https://plato.stanford.edu/entries/russell-paradox/
    image_url: https://cdn0.iconfinder.com/data/icons/network-and-communication-1-8/66/87-512.png

  - name: Investing and Algorithmic Trading
    web_url: https://www.investopedia.com/terms/m/macd.asp
    image_url: https://cdn.onlinewebfonts.com/svg/img_547960.png

thoughts:

